I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 602, in script
    show tsubame happy zorder 1 at f22
  File "game/script.rpy", line 602, in <module>
    show tsubame happy zorder 1 at f22
NameError: name 'f22' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 602, in script
    show tsubame happy zorder 1 at f22
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\ast.py", line 1387, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Program Files\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 602, in <module>
    show tsubame happy zorder 1 at f22
NameError: name 'f22' is not defined

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
Dish Panic 1.0
Mon Nov 20 19:05:24 2023
